# Generated by Django 3.2.13 on 2022-05-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя автора', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию автора', max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(help_text='Введите отчество автора', max_length=150, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(help_text='Введите дату рождения автора', verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='AuthorsPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorsposts', to='posts.author')),
            ],
            options={
                'verbose_name': 'Автор статьи',
                'verbose_name_plural': 'Авторы статьи',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=150, verbose_name='Заголовок статьи')),
                ('text', models.TextField(help_text='Введите текст статьи', verbose_name='Текст статьи')),
                ('authors', models.ManyToManyField(related_name='posts', through='posts.AuthorsPosts', to='posts.Author')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.AddField(
            model_name='authorsposts',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorsposts', to='posts.post'),
        ),
    ]
